apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mydevopsprojectrepo-deployment
spec:
  selector:
    matchLabels:
      app: mydevopsprojectrepo
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mydevopsprojectrepo
    spec:
      containers:
        - name: mydevopsprojectrepo
          image: saurav561/mydevopsprojectrepo:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
